
spring:
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/EasyTravel?serverTimezone=Asia/Seoul
    username: root
    password: Nbyufa1!

easy-travel:
  data:
    currency:
      url: https://api.apilayer.com/fixer
      api-key: vLnpNpDOE4MHD5D7wM6QULz7pcMI03TK

